language: node_js
node_js:
  - '9'
cache: npm
install:
  - npm install -g ganache-cli
before_script:
  - ganache-cli > /dev/null &
script:
  - npm run lint
  - npm run solhint
  - npm test
  - npx solium -d contracts/
  - npm run coverage && cat ./coverage/lcov.info | coveralls