language: node_js
node_js:
  - "8"
before_install:
  - rm -rf node_modules
install:
  - yarn global add ganache-cli
  - yarn install
before_script:
  - ganache-cli > /dev/null &
script:
  - yarn run lint
  - yarn run solhint
  - yarn test
  - npx solium -d contracts/
  - yarn run coverage && cat ./coverage/lcov.info | coveralls
