language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn global add ganache-cli
  - yarn --frozen-lockfile
before_script:
  - ganache-cli > /dev/null &
script:
  - yarn lint
  - yarn solhint
  - yarn test
  - npx solium -d contracts/
  - yarn coverage && cat ./coverage/lcov.info | coveralls
